using System.Collections.Generic;
using UnityEngine;

namespace DriftTogether.World
{
    /// <summary>
    /// Access to the material assets generated by the editor bootstrap
    /// (Assets/_Project/Art/Resources/Materials). Falls back to a runtime
    /// URP Lit material so missing assets can never produce pink geometry.
    /// </summary>
    public static class GameMaterials
    {
        static readonly Dictionary<string, Material> Cache = new Dictionary<string, Material>();

        public static Material Get(string name)
        {
            if (Cache.TryGetValue(name, out var cached) && cached != null)
                return cached;

            var mat = Resources.Load<Material>("Materials/" + name);
            if (mat == null)
            {
                var shader = Shader.Find("Universal Render Pipeline/Lit");
                if (shader == null)
                    shader = Shader.Find("Standard");
                mat = new Material(shader) { color = Color.magenta, name = name + "_fallback" };
                Debug.LogWarning($"Material asset '{name}' missing, using runtime fallback.");
            }
            Cache[name] = mat;
            return mat;
        }

        public static void ApplyTo(GameObject go, string materialName)
        {
            var renderer = go.GetComponent<MeshRenderer>();
            if (renderer != null)
                renderer.sharedMaterial = Get(materialName);
        }
    }

    /// <summary>Warm flickering light for the campfire and mushroom accents.</summary>
    [RequireComponent(typeof(Light))]
    public sealed class FlickerLight : MonoBehaviour
    {
        public float BaseIntensity = 2.4f;
        public float Amplitude = 0.7f;
        public float Speed = 9f;

        Light _light;
        float _seed;

        void Awake()
        {
            _light = GetComponent<Light>();
            _seed = Random.Range(0f, 100f);
        }

        void Update()
        {
            float n = Mathf.PerlinNoise(_seed, Time.time * Speed * 0.1f) * 2f - 1f;
            _light.intensity = BaseIntensity + n * Amplitude
                + Mathf.Sin(Time.time * Speed) * Amplitude * 0.25f;
        }
    }
}
